#!/usr/bin/env node

/**
 * Interactive Configuration Wizard
 * Helps users set up Jira credentials securely
 */

import { stdin as input, stdout as output } from 'process';
import readline from 'readline';
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import os from 'os';
import { fileURLToPath } from 'url';
import { JiraClient } from '../src/jira-client.js';
import { registerAll } from './register-mcp.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rl = readline.createInterface({ input, output });

const colors = {
  reset: '\x1b[0m',
  cyan: '\x1b[36m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  bold: '\x1b[1m',
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

function saveToEnvFile(url, email, token) {
  const envPath = path.resolve(__dirname, '..', '.env');
  const content = `# Jira Configuration generated by setup wizard\nJIRA_URL=${url}\nJIRA_EMAIL=${email}\nJIRA_API_TOKEN=${token}\n`;
  fs.writeFileSync(envPath, content, { mode: 0o600 });
  log(`\n💾 Saved credentials to: ${envPath}`, 'green');
}

function setEnvironmentVariable(name, value) {
  const platform = os.platform();

  try {
    if (platform === 'win32') {
      execSync(`setx ${name} "${value}"`, { stdio: 'pipe' });
      process.env[name] = value;
    } else {
      const shell = process.env.SHELL || '/bin/bash';
      const profileFile = shell.includes('zsh') ? '~/.zshrc' : '~/.bashrc';
      const exportLine = `export ${name}="${value}"`;

      log(`\n📝 Add this line to your ${profileFile}:`, 'yellow');
      log(`   ${exportLine}`, 'cyan');
    }
    return true;
  } catch (error) {
    log(`⚠️  Warning: Could not set system environment variable: ${error.message}`, 'yellow');
    return false;
  }
}

async function main() {
  log('\n╔════════════════════════════════════════════════════════════╗', 'cyan');
  log('║          🎫 JIRA MCP SERVER - CONFIGURATION WIZARD         ║', 'cyan');
  log('╚════════════════════════════════════════════════════════════╝\n', 'cyan');

  log('This wizard will help you configure your Jira connection securely.\n', 'green');

  // Step 1: Jira URL
  log('📍 STEP 1: Jira URL (e.g., https://your-company.atlassian.net)', 'bold');
  let jiraUrl = await question('Enter your Jira URL: ');
  jiraUrl = jiraUrl.trim().replace(/\/+$/, '');
  if (!jiraUrl.startsWith('http://') && !jiraUrl.startsWith('https://')) {
    jiraUrl = `https://${jiraUrl}`;
  }

  // Step 2: Email
  log('\n📧 STEP 2: Atlassian Account Email', 'bold');
  const email = (await question('Enter your Jira email: ')).trim();

  // Step 3: API Token
  log('\n🔑 STEP 3: Jira API Token', 'bold');
  log('Generate one at: https://id.atlassian.com/manage-profile/security/api-tokens', 'cyan');

  output.write('Enter your API token (input is hidden): ');
  const token = await new Promise((resolve) => {
    input.setRawMode(true);
    let tok = '';
    input.on('data', (char) => {
      const str = char.toString('utf8');
      if (str === '\r' || str === '\n') {
        input.setRawMode(false);
        output.write('\n');
        input.removeAllListeners('data');
        resolve(tok.trim());
      } else if (str === '\u0003') {
        process.exit();
      } else if (str === '\u007f' || str === '\b') {
        if (tok.length > 0) {
          tok = tok.slice(0, -1);
          output.write('\b \b');
        }
      } else {
        tok += str;
        output.write('*');
      }
    });
  });

  // Step 4: Test Connection
  log('\n🧪 STEP 4: Testing Connection...', 'bold');
  try {
    const client = new JiraClient({ url: jiraUrl, email, apiToken: token });
    const user = await client.getMyself();

    log('✅ Connection successful!', 'green');
    log(`👤 Authenticated as: ${user.displayName} (${user.emailAddress || email})`, 'green');
    log(`🌐 Timezone:         ${user.timeZone || 'N/A'}`, 'green');

    // Set in current process so subsequent steps know it
    process.env.JIRA_URL = jiraUrl;
    process.env.JIRA_EMAIL = email;
    process.env.JIRA_API_TOKEN = token;
  } catch (error) {
    log(`\n❌ Connection failed: ${error.message}`, 'red');
    log('Please check your URL, email, and API token and try again.\n', 'yellow');
    rl.close();
    process.exit(1);
  }

  // Step 5: Save Configuration
  log('\n💾 STEP 5: Save Configuration', 'bold');
  const saveChoice = await question('Save credentials to local .env file? (Y/n): ');
  if (saveChoice.toLowerCase() !== 'n') {
    saveToEnvFile(jiraUrl, email, token);
  }

  setEnvironmentVariable('JIRA_URL', jiraUrl);
  setEnvironmentVariable('JIRA_EMAIL', email);
  setEnvironmentVariable('JIRA_API_TOKEN', token);

  // Step 6: Register MCP Clients
  log('\n🔌 STEP 6: Register MCP Server', 'bold');
  const regChoice = await question(
    'Register with MCP clients (Copilot CLI, Claude Desktop, Cursor)? (Y/n): '
  );
  if (regChoice.toLowerCase() !== 'n') {
    registerAll();
  }

  log('\n╔════════════════════════════════════════════════════════════╗', 'green');
  log('║                    ✅ SETUP COMPLETE! ✅                   ║', 'green');
  log('╚════════════════════════════════════════════════════════════╝\n', 'green');

  rl.close();
}

main().catch((err) => {
  log(`\n❌ Fatal setup error: ${err.message}`, 'red');
  rl.close();
  process.exit(1);
});
